version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: teste
      MONGO_INITDB_DATABASE: leboncoin
    volumes:
      - mongodb_data:/data/db

  frontend:
    image: node:latest
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    working_dir: /app/frontend
    command: sh -c "npm install && npm start"

  backend:
    image: node:latest
    container_name: backend
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    environment:
      MONGO_URI: mongodb://root:teste@mongodb:27017/leboncoin?authSource=admin
    working_dir: /app/backend
    command: sh -c "npm install && npx nodemon server.js"

volumes:
  mongodb_data:
